import { shuffle } from 'lodash'

export const PROMPTS_LIST = [
  'Someone falls over',
  "Someone's shoe breaks",
  'Dress gets caught in heel',
  'Affrisimo comes on',
  'Rounds needs restarting',
  'Partner missing at the beginning of a round',
  "Someone's hairpiece falls out",
  'Too many couples on the floor',
  'Not enough couples on the floor',
  'Someone is wearing trainers',
  'Illegal beginner outfit',
  'Someone is dancing way below their category',
  'Oxford/Durham/Cambridge in the final',
  'Durham formation team in the final',
  'A team gets their pom poms out',
  'C or below team makes team match final',
  'Quickstep crash',
  'Paso leap alert',
  'Couple out of time in cha',
  "Judges don't move for a whole round of Latin",
  'Cha Cha Slide comes on',
  'Biased judging',
  'Couple goes the wrong way around the floor',
  'Warwick couple makes a final (get in there!!)',
  'A team does coordinated dancing on the sidelines',
  'Gary Foster is present',
  'Two Warwick couples crash',
  "Someone's number falls off",
  'Someone gets hit in the head',
  'Warwick team final in Team Match',
  'The Macarena comes on',
  'Someone attempts the alternative version of the Macarena',
  // 'Pit stop at Maccies',
  // 'Maccies is closed :(',
  'TEAM PHOTO!!!',
  'Someone gets first-rounded',
  'Someone gets knocked out too early',
  'B team beats A team',
  "Someone knocks over someone's stuff",
  'A beginner goes missing before their round',
  'Someone sits in your seat',
  'Someone is danger dancing',
  'Someone asks for a timetable',
  'Someone oversleeps',
  'Emily or Josh fall asleep',
  'Josh has a heart attack',
  'Technical difficulties',
  'Josh gets scared',
  '17 simultaneous be-reals',
  'Emily loses her phone',
  'Josh is sleep deprived',
  'Shark goes missing',
  'Someone screams',
  'Tunnel of finalists comes out',
  'Warwick/Birmingham/Leicester dominate a final',
  'Row of people doing uni work',
  'Not enough chairs',
  'Josh loses something',
  'Someone gets lost',
  'Emily and Josh start attacking each other',
  'Why do we have sharks?',
  // 'Josh and Tom are grandpas',
  'Camera gets lost',
  // 'Tom/Josh get excited over which service station we stop at',
  'Everyone starts crying before midday',
  "Ciara claims it's international women's day",
  'Georgina tells Jess not to run off',
  'Someone thinks Jess has vanished',
  'Former TC expresses gratitude that they are no longer TC',
  'Former TC gets asked TC questions',
  'Jess says she wants to do acro rock and roll',
  'Joe bakes',
]

export const PROMPTS = (): string[] => shuffle(PROMPTS_LIST).slice(0, 25)
